### ISSUE TITLE
Broken in VSC Oct. 2019 Release

### ISSUE THREAD

**Issue by rafegoldberg** [mujichOk/vscode-project-name-in-statusbar#1]
This is a great VSC utility — just what I need to know where I am at a glance (especially when I have a bunch of windows open in zen mode!) Unfortunately the extension seems to have been broken by last month's updates. My version/system details are as follow:

|    VSC    |  Plugin  |              macOS             |
|:---------:|:--------:|:-------------------------------|
| `v1.39.2` | `v1.0.0` | `Darwin x64 19.0.0` (Catalina) |

I _do_ plan to look in to this myself, though I'm no expert when it comes to modding and extending VSC! But I'll post back here if I come across anything that seems to fix the problem. In the meantime, thanks much for this 'lil extension.

**Comment by maliarov** [comment]
@rafegoldberg Thank you for reporting issue, I was skipping for a while maintain of that extension due a high load in current project. Hope to back on it next week. I'll check and try to fix your problem.

**Comment by maliarov** [comment]
can not reproduce on 1.46.1 and upper.

**Comment by rafegoldberg** [comment]
@maliarov just reenabled the extension and lo and behold—it is indeed working again. (Loving the new customization settings too, especially the icon stuff!) Excited to have this back in my VSC status bar. Thanks for your work on this lil guy.
