### ISSUE TITLE
Option to supply the project name from the output of a command or script

### ISSUE THREAD

**Issue by lucono** [mujichOk/vscode-project-name-in-statusbar#2]
Using the output of a command would provide a lot of flexibility for setting the project name without having to implement various additional specific source options for the `projectNameInStatusBar.source` setting. This would allow for instance, having a script that prints the project name which is then displayed in place of the `${project-name}` macro in the template.

This extension has been useful to me, thank you!

**Comment by lucono** [comment]
@maliarov I've submitted pull request #3 to contribute this feature and I'm open to making any adjustments you feel necessary, if you've got some time to look it over. Thanks very much!

**Comment by maliarov** [comment]
@lucono thanks for contributing but it seems that new functionality is out of specific problematic area ext solves.
